version: "3"

services:
    user-manager:
        build:
            context: user-manager
            dockerfile: ./deploy/Dockerfile
        command: uvicorn app.main:app

    catalog:
        build:
            context: catalog
            dockerfile: ./deploy/Dockerfile
        command: ./catalog