version: "3"

services:
    user-manager:
#        image: # путь до docker.registry куда чеерз ci положу
        build:
            context: user-manager
            dockerfile: ./deploy/Dockerfile
        command: python main.py

    catalog:
        image: matiiv/catalog:latest
        command: ./catalog