name: catalog service CI
run-name: catalog ${{ github.actor }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./catalog/Dockerfile
          push: false
          tags: catalog:latest