name: catalog service CI
run-name: catalog ${{ github.actor }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . -f Dockerfile -t catalog
#  deploy:
#    runs-on: ubuntu-22.04