name: catalog service CI
run-name: catalog ${{ github.actor }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
         namme: test
         run: echo ${{ github.action_repository }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./catalog
          file: ./catalog/deploy/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.action_repository }}/catalog:latest