name: catalog service CI
run-name: catalog ${{ github.actor }}

on: [push]

jobs:
  prepare-docker:
    uses: RomanMatiiv/another-one-delivery/.github/workflows/base-prepare-docker.yaml@main
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./catalog
          platforms: linux/amd64,linux/arm64
          file: ./catalog/deploy/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/catalog:0.0.1, ${{ secrets.DOCKERHUB_USERNAME }}/catalog:latest